name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull repositorio
        uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          TAG=$(date +%s)
          docker build -t ${{ secrets.DOCKER_HUB_USER }}/calculadora:$TAG .
          docker tag ${{ secrets.DOCKER_HUB_USER }}/calculadora:$TAG ${{ secrets.DOCKER_HUB_USER }}/calculadora:latest
          docker push ${{ secrets.DOCKER_HUB_USER }}/calculadora:$TAG
          docker push ${{ secrets.DOCKER_HUB_USER }}/calculadora:latest
